export const playersJson = {
  playerDetails: [
    {
      fullName: "Γιώργος Χούσος",
      shirtName: "ΧΟΥΣΟΣ",
      number: "4",
      position: "PG",
      height: "165",
      weight: "60",
      images: [],
    },
    {
      fullName: "Χρήστος Λέσκος",
      shirtName: "LESKOS",
      number: "5",
      position: "PF / C",
      height: "182",
      weight: "79",
      images: [],
    },
    {
      fullName: "Πύρρος Μητρούση",
      shirtName: "ΜΗΤΡΟΥΣΗ",
      number: "6",
      position: "SG / SF",
      height: "178",
      weight: "92",
      images: [],
    },
    {
      fullName: "Γιάννης Μπαρτζώκας",
      shirtName: "BARTZO",
      number: "7",
      position: "SG",
      height: "174",
      weight: "68",
      images: [],
    },
    {
      fullName: "Θοδωρής Μακαρίτης",
      shirtName: "MAKARITIS",
      number: "10",
      position: "PG / SG",
      height: "179",
      weight: "80",
      images: ["mak-front.png"],
    },
    {
      fullName: "Παναγιώτης Βλάχος",
      shirtName: "ΒΛΑΧΟΣ",
      number: "11",
      position: "C",
      height: "195",
      weight: "90",
      images: [],
    },
    {
      fullName: "Δημήτρης Σελεμενάκης",
      shirtName: "SELEMENAKIS",
      number: "12",
      position: "PF / C",
      height: "177",
      weight: "78",
      images: [],
    },
    {
      fullName: "Γιάννης Καντιώτης",
      shirtName: "ΚΑΝΤΙΩΤΗΣ",
      number: "13",
      position: "PG",
      height: "177",
      weight: "80",
      images: [],
    },
    {
      fullName: "Δημήτρης Πατσίδης",
      shirtName: "ΠΑΤΣΙΔΗΣ",
      number: "15",
      position: "C",
      height: "195",
      weight: "92",
      images: [],
    },
    {
      fullName: "Μίλτος Κούρρα",
      shirtName: "ΚΟΥΡΡΑ",
      number: "21",
      position: "SF / PF",
      height: "182",
      weight: "79",
      images: [],
    },
    {
      fullName: "Σταμάτης Σελεμενάκης",
      shirtName: "SELE",
      number: "23",
      position: "SF",
      height: "178",
      weight: "76",
      images: [],
    },
    {
      fullName: "Ηλίας Σπυρόπουλος",
      shirtName: "DUKE",
      number: "24",
      position: "PF",
      height: "179",
      weight: "80",
      images: [],
    },
    {
      fullName: "Γιάννης Σόβολος",
      shirtName: "SOVOLOS",
      number: "29",
      position: "PF / C",
      height: "183",
      weight: "97",
      images: [],
    },
    {
      fullName: "Γιάννης Ντεγιάννης",
      shirtName: "DEJOHN",
      number: "34",
      position: "SF / PF",
      height: "180",
      weight: "93",
      images: [],
    },
  ],
};
